[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Ship-Pines
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Ship-Pines
GtkTheme=oomox-Ship-Pines
IconTheme=oomox-Ship-Pines
MetacityTheme=oomox-Ship-Pines
